const Todo = {
    Tegnologia : [{Name:"Samsung S10e",
                    Id: 1,
                    Tipo: "Mobil",
                    Estado: "Nuevo",
                    Precio: 10000,
                    Disponible: "Si",
                    Img: "./Fotos/S10e.jpg"
                 },
                 {Name: "Xiaomi plus",
                    Id: 2,
                    Tipo: "Mobil",
                    Estado: "Usado",
                    Precio: 8000,
                    Disponible: "Si",
                    Img: "./Fotos/Xiaomi.jpg"
                },
                {Name: "Lapto Dell",
                    Id: 3,
                    Tipo: "Computadora",
                    Estado: "Nuevo",
                    Precio: 50000,
                    Disponible: "Si",
                    Img: "./Fotos/Lapto dell.jpg"
                },
                {Name: "Lapto Lenovo",
                    Id: 4,
                    Tipo: "Computadora",
                    Estado: "Usado",
                    Precio: 40000,
                    Disponible: "Si",
                    Img: "./Fotos/Lenovo.jpg"
                },
                {Name: "Tablet Samsung",
                    Id: 5,
                    Tipo: "Tablet",
                    Estado: "Nuevo",
                    Precio: 15000,
                    Disponible: "Si",
                    Img: "./Fotos/TSamsung.jpg"
                },
                {Name: "Tablet Apple",
                    Id: 6,
                    Tipo: "Tablet",
                    Estado: "Nuevo",
                    Precio: 20000,
                    Disponible: "No",
                    Img: "./Fotos/TApplet.jpg"
                },
                {Name: "Mini Lapto Hp",
                    Id: 7,
                    Tipo: "Mini Lapto",
                    Estado: "Usado",
                    Precio: 25000,
                    Disponible: "No",
                    Img: "./Fotos/Mini hp.jpg"
                },
                {Name: "Mini Lapto Dell",
                    Id: 8,
                    Tipo: "Mini Lapto",
                    Estado: "Nuevo",
                    Precio: 18000,
                    Disponible: "Si",
                    Img: "./Fotos/Mini dell.jpg"
                }     
                ],

    Electrodomesticos : [{Name: "Sofa",
                            Id: 9,
                            Tipo: "Mueble",
                            Estado: "Nuevo",
                            Precio: 9000,
                            Disponible: "Si",
                            Img: "./Fotos/Sofa.jpg"
                        },
                        {Name: "Mesa",
                            Id: 10,
                            Tipo: "Mueble",
                            Estado: "Nuevo",
                            Precio: 6000,
                            Disponible: "Si",
                            Img: "./Fotos/Mesa.png"
                        },
                        {Name: "Cama de 64",
                            Id: 11,
                            Tipo: "Cama",
                            Estado: "Nuevo",
                            Precio: 12000,
                            Disponible: "Si",
                            Img: "./Fotos/Cama.jpg"
                        },
                        {Name: "Cama de 32",
                            Id: 12,
                            Tipo: "Cama",
                            Estado: "Nuevo",
                            Precio: 8000,
                            Disponible: "No",
                            Img: "./Fotos/CamaMediana.jpg"
                        },
                        {Name: "Escoba",
                            Id: 13,
                            Tipo: "Limpieza",
                            Estado: "Nuevo",
                            Precio: 250,
                            Disponible: "Si",
                            Img: "./Fotos/Escoba.jpg"
                        },
                        {Name: "Suape",
                            Id: 14,
                            Tipo: "Limpieza",
                            Estado: "Nuevo",
                            Precio: 250,
                            Disponible: "Si",
                            Img: "./Fotos/Suape.jpg"
                        }
                    ],
    Otros : [{Name: "Toyota",
                Id: 15,
                Tipo: "Carro",
                Estado: "Nuevo",
                Precio: 800000,
                Disponible: "Si",
                Img: "./Fotos/Toyota.jpg"
             },
             {Name: "Guante",
                Id: 16,
                Tipo: "Ejercicio",
                Estado: "Usado",
                Precio: 2000,
                Disponible: "No",
                Img: "./Fotos/Guante.jpg"
             },
             {Name: "Maquina de correr",
                Id: 17,
                Tipo: "Ejercicio",
                Estado: "Nuevo",
                Precio: 22000,
                Disponible: "Si",
                Img: "./Fotos/Correr.jpg"
             },
             {Name: "Polera Blanca",
                Id: 18,
                Tipo: "Polera",
                Estado: "Nuevo",
                Precio: 300,
                Disponible: "Si",
                Img: "./Fotos/Blanca.jpg"
            },
            {Name: "Polera Negra",
               Id: 19,
               Tipo: "Polera",
               Estado: "Nuevo",
               Precio: 300,
               Disponible: "Si",
               Img: "./Fotos/Negra.jpg"
            },
            {Name: "Tenis Nike",
                Id: 20,
                Tipo: "Tenis",
                Estado: "Nuevo",
                Precio: 3000,
                Disponible: "Si",
                Img: "./Fotos/Tenis.jpg"
            }
            ]
}

export default Todo